In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.metrics import (
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

2023-10-12 13:11:31.192430: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "

In [2]:
data = pd.read_csv("../data.csv")
data.head()

,Unnamed: 0.1,Unnamed: 0,Australia,Europe,Brazil,Canada,China,Denmark,Hong Kong,India,Japan,Malaysia
0,0,2010-01-04,0.9133,1.4419,1.7200,1.0377,6.8273,5.1597,7.7555,46.27,92.55,3.396
1,1,2010-01-05,0.9143,1.4402,1.7296,1.0371,6.8258,5.1668,7.7564,46.13,91.48,3.385
2,2,2010-01-06,0.9189,1.4404,1.7292,1.0333,6.8272,5.1638,7.7546,45.72,92.53,3.379
3,3,2010-01-07,0.9168,1.4314,1.7409,1.0351,6.8280,5.1981,7.7539,45.67,93.31,3.368
4,4,2010-01-08,0.9218,1.4357,1.7342,1.0345,6.8274,5.1827,7.7553,45.50,92.70,3.375

In [3]:
data.drop("Unnamed: 0.1", axis=1, inplace=True)
data.rename(columns={"Unnamed: 0": "Date"}, inplace=True)
data["Date"] = pd.to_datetime(data["Date"])
data.set_index("Date", inplace=True)
data.replace(0, np.nan, inplace=True)

In [4]:
data

,Australia,Europe,Brazil,Canada,China,Denmark,Hong Kong,India,Japan,Malaysia
Date,,,,,,,,,,
2010-01-04,0.9133,1.4419,1.7200,1.0377,6.8273,5.1597,7.7555,46.27,92.55,3.3960
2010-01-05,0.9143,1.4402,1.7296,1.0371,6.8258,5.1668,7.7564,46.13,91.48,3.3850
2010-01-06,0.9189,1.4404,1.7292,1.0333,6.8272,5.1638,7.7546,45.72,92.53,3.3790
2010-01-07,0.9168,1.4314,1.7409,1.0351,6.8280,5.1981,7.7539,45.67,93.31,3.3680
2010-01-08,0.9218,1.4357,1.7342,1.0345,6.8274,5.1827,7.7553,45.50,92.70,3.3750
...,...,...,...,...,...,...,...,...,...,...
2019-12-27,0.6978,1.1174,4.0507,1.3073,6.9954,6.6829,7.7874,71.45,109.47,4.1260
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,0.7004,1.1217,4.0152,1.3058,6.9864,6.6589,7.7857,71.30,108.85,4.1053
2019-12-31,0.7030,1.1227,4.0190,1.2962,6.9618,6.6554,7.7894,71.36,108.67,4.0918

In [5]:
data.interpolate(method="linear", limit_direction="forward")

,Australia,Europe,Brazil,Canada,China,Denmark,Hong Kong,India,Japan,Malaysia
Date,,,,,,,,,,
2010-01-04,0.913300,1.441900,1.720000,1.0377,6.8273,5.1597,7.755500,46.27,92.550000,3.3960
2010-01-05,0.914300,1.440200,1.729600,1.0371,6.8258,5.1668,7.756400,46.13,91.480000,3.3850
2010-01-06,0.918900,1.440400,1.729200,1.0333,6.8272,5.1638,7.754600,45.72,92.530000,3.3790
2010-01-07,0.916800,1.431400,1.740900,1.0351,6.8280,5.1981,7.753900,45.67,93.310000,3.3680
2010-01-08,0.921800,1.435700,1.734200,1.0345,6.8274,5.1827,7.755300,45.50,92.700000,3.3750
...,...,...,...,...,...,...,...,...,...,...
2019-12-27,0.697800,1.117400,4.050700,1.3073,6.9954,6.6829,7.787400,71.45,109.470000,4.1260
2019-12-28,0.698667,1.118833,4.038867,1.3068,6.9924,6.6749,7.786833,71.40,109.263333,4.1191
2019-12-29,0.699533,1.120267,4.027033,1.3063,6.9894,6.6669,7.786267,71.35,109.056667,4.1122
2019-12-30,0.700400,1.121700,4.015200,1.3058,6.9864,6.6589,7.785700,71.30,108.850000,4.1053
2019-12-31,0.703000,1.122700,4.019000,1.2962,6.9618,6.6554,7.789400,71.36,108.670000,4.0918

In [6]:
data.interpolate(method="linear", limit_direction="forward", inplace=True)
LOOK_BACK = 30
PREDICT_DAY = 1
SPLIT_RATIO = 0.8

In [7]:
def Create_Data(
    data, lookback=LOOK_BACK, pred_len=PREDICT_DAY, split_ratio=SPLIT_RATIO
):
    if lookback < 2:
        print("ERROR: Lookback too small")
        return -1

    # declarations

    x = {}
    y = {}
    xtr = {}
    xt = {}
    ytr = {}
    yt = {}
    scalers = {}

    # Creating stepped data

    for i in data.columns:
        xtemp = pd.DataFrame(data[i])
        for j in range(1, lookback + 1):
            xtemp[i + str(j)] = data[i].shift(-1 * j)
        x[i] = xtemp.dropna()

    # Splitting data into x and y

    for i in x.keys():
        y[i] = pd.DataFrame(x[i].iloc[:, -pred_len])
        x[i] = x[i].iloc[:, :-pred_len]

    # Normalizing x and y values

    for i in x.keys():
        scalers[i + "_x"] = MinMaxScaler(feature_range=(0, 1))
        x[i] = scalers[i + "_x"].fit_transform(x[i])
        scalers[i + "_y"] = MinMaxScaler(feature_range=(0, 1))
        y[i] = scalers[i + "_y"].fit_transform(y[i])

    # setting train and test sizes

    tr_len = int(split_ratio * y["India"].shape[0])
    t_len = y["India"].shape[0] - tr_len

    # creating training and testing data

    for i in x.keys():
        xtr[i] = x[i][:tr_len]
        ytr[i] = y[i][:tr_len]
        xt[i] = x[i][-t_len:]
        yt[i] = y[i][-t_len:]

    # returning pertinent data

    return x, y, xtr, xt, ytr, yt, scalers

In [8]:
x, y, xtr, xt, ytr, yt, scalers = Create_Data(data)

In [9]:
def Create_model(x, lookback=LOOK_BACK):
    models = {}
    for key in x.keys():
        input_dim = x[key].shape[1]

        model = Sequential()

        # Encoder
        model.add(Dense(128, input_shape=(input_dim,), activation="relu"))
        model.add(Dense(64, activation="relu"))
        model.add(Dropout(0.2))

        model.add(Dense(32, activation="relu"))

        # Decoder
        model.add(Dropout(0.2))
        model.add(Dense(64, activation="relu"))
        model.add(Dense(128, activation="relu"))
        model.add(Dense(input_dim, activation="linear"))

        model.compile(optimizer="adam", loss="mean_squared_error")

        models[key] = model

    return models

In [10]:
m = Create_model(x)

2023-10-12 13:11:33.049564: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.073169: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.073592: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.077406: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.077872: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.078198: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.182528: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.182776: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.182974: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-12 13:11:33.183133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 732 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-10-12 13:11:33.183706: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.

In [11]:
def Execute_model(model, xtr, ytr, xt, yt, scaler):
    MAPE = {}
    MAE = {}
    MSE = {}
    for i in model.keys():
        print(i)
        es = EarlyStopping(monitor="val_loss", mode="min", verbose=1, patience=10)
        reduce_lr = ReduceLROnPlateau(
            monitor="val_loss", factor=0.2, patience=5, min_lr=0.0001
        )

        # Here, we train the autoencoder using xtr[i] as both input and target
        model[i].fit(
            xtr[i],
            xtr[i],
            epochs=100,
            batch_size=64,
            verbose=1,
            validation_split=0.2,
            callbacks=[es, reduce_lr],
        )

        # Use the model to predict/decode the test set and calculate the reconstruction error
        temp = model[i].predict(xt[i])
        pred = scaler[i + "_x"].inverse_transform(temp)
        act = scaler[i + "_x"].inverse_transform(xt[i])

        MSE[i] = mean_squared_error(act, pred)
        MAE[i] = mean_absolute_error(act, pred)
        MAPE[i] = mean_absolute_percentage_error(act, pred)

    results = pd.DataFrame([MSE, MAE, MAPE])
    results["Metric"] = ["MSE", "MAE", "MAPE"]
    results.set_index("Metric", inplace=True)

    return results

In [12]:
result = Execute_model(m, xtr, ytr, xt, yt, scalers)

Australia
Epoch 1/100

2023-10-12 13:11:34.626246: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5578ad457f30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-10-12 13:11:34.626280: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1660 Ti, Compute Capability 7.5
2023-10-12 13:11:34.636763: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-10-12 13:11:34.665982: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902
2023-10-12 13:11:34.798602: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

37/37 [==============================] - 2s 11ms/step - loss: 0.1270 - val_loss: 0.0021 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0140 - val_loss: 5.6090e-04 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0072 - val_loss: 8.2139e-04 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0047 - val_loss: 0.0014 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0042 - val_loss: 0.0015 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0035 - val_loss: 0.0018 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0028 - val_loss: 0.0012 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0028 - val_loss: 0.0012 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0026 - val_loss: 0.0012 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0025 - val_loss: 0.0013 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0027 - val_loss: 0.0013 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0024 - val_loss: 0.0012 - lr: 2.0000e-04
Epoch 12: early stopping
23/23 [==============================] - 0s 2ms/step
Europe
Epoch 1/100
37/37 [==============================] - 2s 9ms/step - loss: 0.1209 - val_loss: 0.0027 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0104 - val_loss: 0.0019 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0063 - val_loss: 0.0022 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0053 - val_loss: 0.0030 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0043 - val_loss: 0.0021 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0037 - val_loss: 0.0026 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0035 - val_loss: 0.0019 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0032 - val_loss: 0.0021 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0029 - val_loss: 0.0021 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0031 - val_loss: 0.0022 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0028 - val_loss: 0.0021 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0029 - val_loss: 0.0022 - lr: 2.0000e-04
Epoch 12: early stopping
23/23 [==============================] - 0s 2ms/step
Brazil
Epoch 1/100
37/37 [==============================] - 2s 10ms/step - loss: 0.0404 - val_loss: 0.0124 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0044 - val_loss: 0.0211 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0027 - val_loss: 0.0226 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0021 - val_loss: 0.0236 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0020 - val_loss: 0.0272 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0015 - val_loss: 0.0306 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0014 - val_loss: 0.0306 - lr: 2.0000e-04
Epoch 8/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0013 - val_loss: 0.0345 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0014 - val_loss: 0.0331 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0012 - val_loss: 0.0370 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0012 - val_loss: 0.0298 - lr: 2.0000e-04
Epoch 11: early stopping
23/23 [==============================] - 0s 2ms/step
Canada
Epoch 1/100
37/37 [==============================] - 2s 10ms/step - loss: 0.0440 - val_loss: 0.0104 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0047 - val_loss: 0.0085 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0029 - val_loss: 0.0244 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0021 - val_loss: 0.0252 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0018 - val_loss: 0.0470 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0016 - val_loss: 0.0332 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0014 - val_loss: 0.0380 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0013 - val_loss: 0.0331 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0013 - val_loss: 0.0386 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0013 - val_loss: 0.0378 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0012 - val_loss: 0.0386 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0012 - val_loss: 0.0358 - lr: 2.0000e-04
Epoch 12: early stopping
23/23 [==============================] - 0s 2ms/step
China
Epoch 1/100
37/37 [==============================] - 2s 9ms/step - loss: 0.0353 - val_loss: 0.0262 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0032 - val_loss: 0.0245 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0019 - val_loss: 0.0327 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0015 - val_loss: 0.0335 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0013 - val_loss: 0.0426 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0011 - val_loss: 0.0358 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 9.8922e-04 - val_loss: 0.0356 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 6ms/step - loss: 8.1534e-04 - val_loss: 0.0321 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 6ms/step - loss: 8.4247e-04 - val_loss: 0.0320 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 6ms/step - loss: 7.8541e-04 - val_loss: 0.0325 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 7ms/step - loss: 7.4972e-04 - val_loss: 0.0325 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 7ms/step - loss: 7.5670e-04 - val_loss: 0.0311 - lr: 2.0000e-04
Epoch 12: early stopping
23/23 [==============================] - 0s 2ms/step
Denmark
Epoch 1/100
37/37 [==============================] - 2s 9ms/step - loss: 0.0529 - val_loss: 0.0291 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0062 - val_loss: 0.0251 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0044 - val_loss: 0.0322 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0036 - val_loss: 0.0331 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0028 - val_loss: 0.0467 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0026 - val_loss: 0.0493 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0024 - val_loss: 0.0553 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0024 - val_loss: 0.0555 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0024 - val_loss: 0.0508 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0022 - val_loss: 0.0536 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0020 - val_loss: 0.0531 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0021 - val_loss: 0.0490 - lr: 2.0000e-04
Epoch 12: early stopping
23/23 [==============================] - 0s 2ms/step
Hong Kong
Epoch 1/100
37/37 [==============================] - 2s 10ms/step - loss: 0.0124 - val_loss: 0.0061 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0031 - val_loss: 0.0079 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0028 - val_loss: 0.0054 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0023 - val_loss: 0.0094 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0020 - val_loss: 0.0098 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0018 - val_loss: 0.0108 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0017 - val_loss: 0.0108 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0016 - val_loss: 0.0126 - lr: 0.0010
Epoch 9/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0015 - val_loss: 0.0096 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0015 - val_loss: 0.0113 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0014 - val_loss: 0.0100 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0015 - val_loss: 0.0112 - lr: 2.0000e-04
Epoch 13/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0014 - val_loss: 0.0108 - lr: 2.0000e-04
Epoch 13: early stopping
23/23 [==============================] - 0s 2ms/step
India
Epoch 1/100
37/37 [==============================] - 2s 9ms/step - loss: 0.0597 - val_loss: 0.0174 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0059 - val_loss: 0.0140 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0036 - val_loss: 0.0330 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0027 - val_loss: 0.0309 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0022 - val_loss: 0.0437 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0021 - val_loss: 0.0455 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0016 - val_loss: 0.0359 - lr: 0.0010
Epoch 8/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0014 - val_loss: 0.0369 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0014 - val_loss: 0.0333 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0013 - val_loss: 0.0365 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0013 - val_loss: 0.0355 - lr: 2.0000e-04
Epoch 12/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0012 - val_loss: 0.0374 - lr: 2.0000e-04
Epoch 12: early stopping
23/23 [==============================] - 0s 2ms/step
Japan
Epoch 1/100
37/37 [==============================] - 2s 10ms/step - loss: 0.0678 - val_loss: 0.0090 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0068 - val_loss: 0.0183 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0046 - val_loss: 0.0278 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0035 - val_loss: 0.0254 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0029 - val_loss: 0.0361 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0029 - val_loss: 0.0318 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0024 - val_loss: 0.0299 - lr: 2.0000e-04
Epoch 8/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0024 - val_loss: 0.0333 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0024 - val_loss: 0.0331 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0023 - val_loss: 0.0343 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0022 - val_loss: 0.0358 - lr: 2.0000e-04
Epoch 11: early stopping
23/23 [==============================] - 0s 2ms/step
Malaysia
Epoch 1/100
37/37 [==============================] - 2s 10ms/step - loss: 0.0390 - val_loss: 0.0216 - lr: 0.0010
Epoch 2/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0042 - val_loss: 0.0308 - lr: 0.0010
Epoch 3/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0028 - val_loss: 0.0532 - lr: 0.0010
Epoch 4/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0021 - val_loss: 0.0517 - lr: 0.0010
Epoch 5/100
37/37 [==============================] - 0s 5ms/step - loss: 0.0019 - val_loss: 0.0714 - lr: 0.0010
Epoch 6/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0017 - val_loss: 0.0681 - lr: 0.0010
Epoch 7/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0014 - val_loss: 0.0616 - lr: 2.0000e-04
Epoch 8/100
37/37 [==============================] - 0s 6ms/step - loss: 0.0015 - val_loss: 0.0589 - lr: 2.0000e-04
Epoch 9/100
37/37 [==============================] - 0s 8ms/step - loss: 0.0013 - val_loss: 0.0633 - lr: 2.0000e-04
Epoch 10/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0013 - val_loss: 0.0577 - lr: 2.0000e-04
Epoch 11/100
37/37 [==============================] - 0s 7ms/step - loss: 0.0012 - val_loss: 0.0651 - lr: 2.0000e-04
Epoch 11: early stopping
23/23 [==============================] - 0s 2ms/step

In [13]:
result

,Australia,Europe,Brazil,Canada,China,Denmark,Hong Kong,India,Japan,Malaysia
Metric,,,,,,,,,,
MSE,0.000423,0.000345,0.421802,0.009701,0.047528,0.173083,0.000635,48.941972,86.066015,0.116573
MAE,0.016162,0.013421,0.640476,0.097679,0.198196,0.406992,0.024537,6.925121,9.218311,0.339143
MAPE,0.022716,0.011327,0.168098,0.074378,0.028889,0.062371,0.003130,0.099580,0.083859,0.082841

In [14]:
import json
import os

# Define the filename
filename = "../results.json"

# Check if the file exists
if os.path.isfile(filename):
    # If the file exists, load the existing data
    with open(filename, "r") as f:
        data = json.load(f)
else:
    # If the file doesn't exist, create an empty dictionary
    data = {}

# Add the result to the dictionary
data["Autoencoder"] = result.to_dict()

# Write the dictionary to the file
with open(filename, "w") as f:
    json.dump(data, f)

: